# Generated by Django 5.2.2 on 2025-06-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wiss', '0005_eventarea_event_eventdate_eventscategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='site',
        ),
        migrations.RemoveField(
            model_name='eventarea',
            name='site',
        ),
        migrations.RemoveField(
            model_name='eventscategory',
            name='site',
        ),
    ]
