# Generated by Django 5.2.2 on 2025-06-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wiss', '0007_alter_category_id_alter_event_id_alter_eventarea_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DefaultPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
