# Generated by Django 5.2.2 on 2025-06-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wiss', '0009_contentgridblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentGridBlock',
        ),
    ]
